### ISSUE TITLE
[1.7.11] Possible conflict with XSkill/XLib?

### ISSUE THREAD

**Issue by ARandwulf** [l33tmaan/EFRecipes#16]
Hello there!

It seems I have a very specific conflict between XSkills and Culinary Artillery/Expanded Food.

Whenever I try to cook hot pastas in a pot with boiled eggs in the recipes, as soon as I add the eggs to the pot, I CtD.

EDIT: just adding the dreaded boiled things to a pot makes it CtD. I also look for a possible fix on the XSkills forums.

`Here is the crash log:

Running on 64 bit Windows with 32 GB RAM 
Game Version: v1.17.11 (Stable)
2023-04-02 10:28:56: Critical error occurred in the following mod: xskills@0.7.0-pre.1
Loaded Mods: acorns@0.5.1, aculinaryartillery@1.0.11, advancedsmithing@1.3.0, weaponpacka@1.3.1, ancienttools@1.5.1, atwatersedge@1.2.1, bettercrates@1.5.3, betterruins@0.0.7, Ceramos@0.2.4, chiseltools@1.7.2, creaturescan@1.0.0, drdecor@1.0.0, extrachests@1.6.2, fancydoors@1.1.1, morecrops@1.0.2, fireclayfrompanning@1.0.0, furniturelibrary@1.0.6, weaponpackg@1.0.1, HQ@1.9.1, medieval@1.3.43, meteoricexpansion@1.2.2, leadroof@1.2.4, MoreTorchHolders@1.0.0, naturalpatcheslite@0.0.3, necessariesfix@1.1.3-rc.1, primitivesurvival@3.1.2, realshingles@1.0.2, shinglesandthethings@1.0.2-rc.1, rustandrails@1.0.4, sortablestorage@1.6.0, spyglass@0.4.5, thecritterpack@0.7.6, tradeomat@1.6.3, translocatorengineeringredux@1.3.0, usefuldrifterloot@1.0.2, game@1.17.11, wildcrafttrees@1.1.4, wildcraft@1.5.1, betterfirepit@1.0.0, calendar@1.0.0, carryon@0.10.3, cuniculture@1.0.1, expandedfoods@1.6.4, fromgoldencombs@1.3.15, hudclock@2.8.0, lecheesedecubique@1.0.0, lichen@1.6.2, miningtools@1.1.4, moreicons@1.0.3, outlawmodcan@1.0.4, petai@1.5.5, playercorpse@1.5.5, recycleclothes@1.0.0, stonequarry@2.0.0-rc.4, tprunes@1.0.7, vanvar@2.0.1, wildfarming@1.2.1, creative@1.17.11, vsquest@0.4.0, survival@1.17.11, woodbarrels@1.0.4, woodchests@1.0.4, workbenchexpansion@1.5.1, xlib@0.7.0-pre.1, metalrecovery@0.1.18-rc.2, em@1.1.0, feverstonewilds@1.1.0, wolftaming@1.5.4, xskills@0.7.0-pre.1, bricklayers@1.2.3
Involved Harmony IDs: XSkillsPatch, com.jakecool19.efrecipes.cookingoverhaul
System.NullReferenceException: Object reference not set to an instance of an object.
   at XSkills.CookingRecipePatch.MatchesPrefix(CookingRecipe __instance, Boolean& __result, ItemStack[] inputStacks, Int32& quantityServings)
   at Vintagestory.GameContent.CookingRecipe.Matches_Patch1(CookingRecipe this, ItemStack[] inputStacks, Int32& quantityServings)
   at Vintagestory.GameContent.BlockCookingContainer.GetMatchingCookingRecipe(IWorldAccessor world, ItemStack[] stacks) in VSSurvivalMod\Systems\Cooking\BlockCookingContainer.cs:line 239
   at Vintagestory.GameContent.BlockCookingContainer.GetOutputText_Patch2(BlockCookingContainer this, IWorldAccessor world, ISlotProvider cookingSlotsProvider, ItemSlot inputSlot)
   at Vintagestory.GameContent.InventorySmelting.GetOutputText_Patch2(InventorySmelting this)
   at Vintagestory.GameContent.BlockEntityFirepit.SetDialogValues_Patch1(BlockEntityFirepit this, ITreeAttribute dialogTree)
   at Vintagestory.GameContent.BlockEntityFirepit.OnSlotModifid(Int32 slotid) in VSSurvivalMod\BlockEntity\Firepit\BEFirepit.cs:line 141
   at System.Action`1.Invoke(T obj)
   at Vintagestory.API.Common.InventoryBase.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 480
   at Vintagestory.GameContent.InventorySmelting.DidModifyItemSlot(ItemSlot slot, ItemStack extractedStack) in VSSurvivalMod\Inventory\InventorySmelting.cs:line 116
   at Vintagestory.API.Common.ItemSlot.OnItemSlotModified(ItemStack sinkStack) in VintagestoryApi\Common\Inventory\ItemSlot.cs:line 424
   at Vintagestory.GameContent.ItemSlotWatertight.ActivateSlotLeftClick(ItemSlot sourceSlot, ItemStackMoveOperation& op) in VSSurvivalMod\Inventory\ItemSlotWatertight.cs:line 103
   at Vintagestory.API.Common.InventoryBase.ActivateSlot(Int32 slotId, ItemSlot sourceSlot, ItemStackMoveOperation& op) in VintagestoryApi\Common\Inventory\InventoryBase.cs:line 448
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.SlotClick(ICoreClientAPI api, Int32 slotId, EnumMouseButton mouseButton, Boolean shiftPressed, Boolean ctrlPressed, Boolean altPressed) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 980
   at Vintagestory.API.Client.GuiElementItemSlotGridBase.OnMouseDownOnElement(ICoreClientAPI api, MouseEvent args) in VintagestoryApi\Client\UI\Elements\Impl\Interactive\Inventory\GuiElementItemSlotGridBase.cs:line 773
   at Vintagestory.API.Client.GuiElement.OnMouseDown(ICoreClientAPI api, MouseEvent mouse) in VintagestoryApi\Client\UI\Elements\Impl\GuiElement.cs:line 638
   at Vintagestory.API.Client.GuiComposer.OnMouseDown(MouseEvent mouseArgs) in VintagestoryApi\Client\UI\GuiComposer.cs:line 459
   at Vintagestory.API.Client.GuiDialog.OnMouseDown(MouseEvent args) in VintagestoryApi\Client\UI\Dialog\GuiDialog.cs:line 536
   at Vintagestory.Client.NoObf.GuiManager.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\Systems\Gui\GuiManager.cs:line 394
   at Vintagestory.Client.NoObf.ClientMain.OnMouseDown(MouseEvent args) in VintagestoryLib\Client\ClientMain.cs:line 2251
   at Vintagestory.Client.NoObf.ClientPlatformWindows.Mouse_ButtonDown(Object sender, MouseButtonEventArgs e) in VintagestoryLib\Client\ClientPlatform\Input.cs:line 220
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.Platform.Windows.WinGLNative.WindowProcedure(IntPtr handle, WindowMessage message, IntPtr wParam, IntPtr lParam) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 792
   at OpenTK.Platform.Windows.Functions.DispatchMessage(MSG& msg)
   at OpenTK.Platform.Windows.WinGLNative.ProcessEvents() in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\Platform\Windows\WinGLNative.cs:line 1554
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second) in C:\Users\Nexrem\Desktop\transfer\opentk\src\OpenTK\GameWindow.cs:line 368
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs)
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93

Event Log entries containing Vintagestory.exe, the latest 3
==================================
{ TimeGenerated = 2023-03-31 22:10:11, Site = , Source = Windows Error Reporting, Message = Fault bucket 1431080498583360532, type 5
Event Name: RADAR_PRE_LEAK_64
Response: Not available
Cab Id: 0

Problem signature:
P1: Vintagestory.exe
P2: 1.17.11.0
P3: 10.0.19045.2.0.0
P4: 
P5: 
P6: 
P7: 
P8: 
P9: 
P10: 

Attached files:
\\?\C:\Users\orand\AppData\Local\Temp\RDR19C6.tmp\empty.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19D7.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19D8.tmp.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER19F4.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER1A33.tmp.txt

These files may be available here:

Analysis symbol: 
Rechecking for solution: 0
Report Id: 421adc3c-fa44-411e-8a02-0deb81cd4f9a
Report Status: 268435456
Hashed bucket: a386333e91cb17c6d3dc38219b0cd414
Cab Guid: 0 }
`
 I updated all of them to the latest version, to no avail.

(I suppose it is all about the XP/Skill assigned to the action, but still).

Thank you for your return on this! 
Godspeed, l33tman.

​

**Comment by l33tmaan** [comment]
Thank you for this! However, if I'm reading that crash right then the source of the bug is actually on XSkills' end. I'm always happy to receive any code they need in order to function, but this one might be outside the scope of EF. If I'm proven wrong I'll try to fix it!

**Comment by ARandwulf** [comment]
Sadly, XSkill/XLib are focusing on the spiffy 1.18 and might not go back to
fix it, but one can hope that they'll look out for that problem. Thanks for
your return and for your work making meal prep a bit more fun!

**Comment by l33tmaan** [comment]
Did XSkills ever fix this?
