### ISSUE TITLE
Expanded Foods (1.6.7) Crashes game on new .NET7 release (1.18.8)

### ISSUE THREAD

**Issue by Rivernoodl** [l33tmaan/EFRecipes#19]
Installed the new Client and updated both a Culinary Artillery and Expanded Foods to the .NET7 Version.  Unfortunately, this mod is crashing the game at world generation, even when starting a fresh world.

> Running on 64 bit Windows with 32687 MB RAM
> Game Version: v1.18.8 (Stable)
> 8/9/2023 6:19:09 PM: Critical error occurred
> Loaded Mods: arrowheadsrecovery_fork@1.0.0, beardeddragons@1.0.0, betterarchery@3.0.0, bettertraders@0.0.2, extrainfo@1.4.0, giantgouramis@1.0.1, knappingmastery@1.0.1, meteoricexpansion@1.2.4, millwright@1.0.7, PartialLandslides@1.0.0, primitivesurvival@3.2.6, rainfrogs@1.2.0, rpgitemrarity@1.0.4, sfaws@1.0.0, sortablestorage@1.9.0, unterra@1.0.0, translocatorengineeringredux@1.4.5, game@1.18.8, wildcraft@1.6.6, zoombuttonreborn@1.4.0, alchemy@1.6.15, altmapiconrenderer@1.2.1, arrowsmelt@1.0.0, canbeignited@1.1.0, divisionoflabor@1.0.5, easylightlevels@1.0.3, moreicons@1.0.4, naturalnight@2.1.0, nohands@0.1.1, nemi@1.1.0, prospecttogether@1.1.0, creative@1.18.8, survival@1.18.8, waypointtogether@1.0.1, wildfarmingrevival@1.1.0, xlib@0.7.4, bugnetcompatibility@1.0.1, em@2.2.2, koboldplayermodel@1.0.0, xskills@0.7.5, moreroads@1.5.2
> System.Exception: Don't know how to instantiate item of class 'ExpandedFood' did you forget to register a mapping?
>    at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in VintagestoryLib\Common\ClassRegistry.cs:line 273
>    at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
>    at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in VintagestoryLib\Client\Systems\Startup.cs:line 580
>    at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in VintagestoryLib\Client\Systems\Startup.cs:line 392
>    at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in VintagestoryLib\Client\Systems\Startup.cs:line 334
>    at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in VintagestoryApi\Common\TyronThreadPool.cs:line 108
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
> 
> Event Log entries containing Vintagestory.exe, the latest 3
> ==================================
> { TimeGenerated = 8/9/2023 6:15:10 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
> Faulting module name: openal32.dll, version: 1.23.0.0, time stamp: 0x63dd31ad
> Exception code: 0x40000015
> Fault offset: 0x00000000000df046
> Faulting process id: 0x27f8
> Faulting application start time: 0x01d9cb032bca5441
> Faulting application path: C:\Users\ggang\AppData\Roaming\Vintagestory\Vintagestory.exe
> Faulting module path: C:\Users\ggang\AppData\Roaming\Vintagestory\Lib\openal32.dll
> Report Id: b5691195-7b01-479c-b418-687e5cb66bb7
> Faulting package full name: 
> Faulting package-relative application ID:  }
> --------------
> { TimeGenerated = 8/9/2023 6:14:58 PM, Site = , Source = Application Error, Message = Faulting application name: Vintagestory.exe, version: 1.18.8.0, time stamp: 0x6492041a
> Faulting module name: KERNELBASE.dll, version: 10.0.19041.3324, time stamp: 0x6967c799
> Exception code: 0xe0434352
> Fault offset: 0x000000000002cf19
> Faulting process id: 0x27f8
> Faulting application start time: 0x01d9cb032bca5441
> Faulting application path: C:\Users\ggang\AppData\Roaming\Vintagestory\Vintagestory.exe
> Faulting module path: C:\Windows\System32\KERNELBASE.dll
> Report Id: 8e6eee11-0492-477a-9ff5-bc2120854cc5
> Faulting package full name: 
> Faulting package-relative application ID:  }
> --------------
> { TimeGenerated = 8/9/2023 6:14:58 PM, Site = , Source = .NET Runtime, Message = Application: Vintagestory.exe
> CoreCLR Version: 7.0.1023.36312
> .NET Version: 7.0.10
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.Exception: Don't know how to instantiate item of class 'ExpandedFood' did you forget to register a mapping?
>    at Vintagestory.Common.ClassRegistry.CreateItem(String itemClass) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\ClassRegistry.cs:line 273
>    at Vintagestory.Common.ItemTypeNet.ReadItemTypePacket(Packet_ItemType packet, IWorldAccessor world, ClassRegistry registry) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Common\Network\ItemTypeNet.cs:line 19
>    at Vintagestory.Client.NoObf.ClientSystemStartup.PopulateItems(List`1 items, Int32 listSize) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 580
>    at Vintagestory.Client.NoObf.ClientSystemStartup.LoadItemTypes() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 392
>    at Vintagestory.Client.NoObf.ClientSystemStartup.HandleServerAssets_Step1() in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryLib\Client\Systems\Startup.cs:line 334
>    at Vintagestory.API.Common.TyronThreadPool.<>c__DisplayClass12_0.<QueueTask>b__0(Object a) in C:\Users\Tyron\Documents\vintagestory\game\VintagestoryApi\Common\TyronThreadPool.cs:line 108
>    at System.Threading.QueueUserWorkItemCallback.Execute()
>    at System.Threading.ThreadPoolWorkQueue.Dispatch()
>    at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
>  }

**Comment by Rivernoodl** [comment]
Update: Turns out the issue is related to A Culinary Artillery, and not Expanded foods.  Make sure that when changing from the .NET4 to the .NET7 version that A Culinary Artillery is deleted from your mod folder first, since they share the same version number and Vintage Story does not recognize them as separate versions.
